config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get "about", to: "pages#about"
  
  resources :articles

  get "signup", to: "users#new"
  resources :users, except: [:new]
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :categories

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 5 }
  validates :description, presence: true, length: { minimum: 10 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_secure_password
  has_many :articles, dependent: :destroy
  validates :username, presence: true, uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 26 }
  validates :email, presence: true, uniqueness: { case_sensitive: false },
                    length: { maximum: 40 },
                    format: { with: URI::MailTo::EMAIL_REGEXP }
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
      if !logged_in?
        flash[:alert] = "You must be login to perform that action"
        redirect_to login_path
      end
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        @articles = Article.paginate(page: params[:page], per_page: 4)
    end
    
    def show
    end
  
    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:notice] = "Article created successfully"
            redirect_to @article
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @article.update(article_params)
            flash[:notice] = "Article updated successfully"
            render :show
        else
            render :new
        end
    end

    def destroy
        @article.destroy
        flash[:notice] = "Article deleted successfully"
        redirect_to articles_path
    end

    private
    
    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end

    def set_article
        @article = Article.find(params[:id])
    end

    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:alert] = "You can only delete your own articles"
        redirect_to @article
      end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show, :edit, :destroy]
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index 
    @categories = Category.paginate(page: params[:page], per_page: 4)
  end

  def new 
    @category = Category.new
  end

  def edit
  end

  def update
    if @category.update(category_params) 
      flash[:notice] = "Category updated successfully"
      redirect_to @category
    else
      render :new
    end
  end

  def destroy
    @category.destroy
    flash[:notice] = "Category deleted successfully"
    redirect_to categories_path
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was succesfuly created"
      redirect_to @category
    else
      render :new
    end
  end

  def show 
    @articles = @category.articles.paginate(page: params[:page], per_page: 4)
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end

  def set_category
    @category = Category.find(params[:id])
  end
  
end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to articles_path if logged_in?
    end
     
    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end
    
    def create
        session_params = params[:session]
        user = User.find_by(username: session_params[:username].downcase)
        
        if user && user.authenticate(session_params[:password])
            session[:user_id] = user.id 
            flash[:notice] = "Logged in successfully"
            redirect_to articles_path
        else
            flash.now[:alert] = "Check your username or password" 
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out successfully"
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :show, :update, :destroy]
    before_action :require_user, only: [:edit, :update, :destroy]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def new
        @user = User.new
    end

    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end

    def edit
    end

    def show
        @articles = @user.articles.paginate(page: params[:page], per_page: 10)
    end

    def update
        if @user.update(user_params)
            flash[:notice] = "Account was successfully updated"
            redirect_to @user
        else
            render :edit
        end
    end

    def destroy
      @user.destroy
      session[:user_id] = nil if @user == current_user
      flash[:notice] = "Account and articles successfully deleted"
      redirect_to articles_path
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "Hello #{@user.username}, you have sign up successfully"
            redirect_to articles_path
        else
            render :new
        end 
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
      if @user != current_user && !current_user.admin?
        flash[:notice] = "You can only edit your own profile"
        redirect_to @user
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = {size: 80} )
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_articles.html.erb
<div class="container">
  <div class="row justify-content-center mt-4 ">
    <% @articles.each do |article| %>
      <div class="col-10 col-md-6">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            by <%= link_to article.user.username, article.user %>
            <% if article.categories.any?%>
              <div class="mt-2">
                <%= render article.categories %>
              </div>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article, class: "text-success" %> </h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article, class: "btn btn-outline-success" %> 
            <% if logged_in? %>
              <% if article.user == current_user %>
                <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %> 
              <% end %>
              <% if article.user == current_user || current_user.admin? %>
                <%= link_to "Delete", article, method: :delete, class: "btn btn-outline-danger", data: { confirm: "Are you sure?" } %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, edited 
            <%= time_ago_in_words(article.updated_at) %> ago
            </small>
          </div>
        </div>
      </div>
    <% end %> 
  </div>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "shared/errors", object: @article %>
      <%= form_with(model: @article, class: "shadow p-3 bg-light rounded", local: true) do |form| %>
        <div class="form-group row" justify-content>
          <%= form.label :title, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= form.text_field :title, placeholder: "title", class: "form-control shadow rounded" %>
          </div>
        </div>
        <div class="form-group row">
          <%= form.label :description, class: "col-2 col-form-label" %>
          <div class="col-10">
              <%= form.text_area :description, placeholder: "description", rows: 6, class: "form-control shadow rounded" %>
          </div>
        </div>
        <div class="form-group row">
          <%= form.label :category, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= form.collection_select(:category_ids, Category.all, :id, :name, {prompt: "Select category"}, 
            {multiple: true, size: Category.count, class: "custom-select shadow rounded"}) %>
          </div>
        </div>
        <div class="row justify-content-center">
          <%= form.submit class: "btn btn-outline-success shadow rounded" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="text-center mt-4">
      <%= link_to "[ Return to articles list ]", articles_path %> 
  </div>
</div>

app/views/articles/edit.html.erb
<div>
    <h1 class="text-center mt-4">Edit article</h1>
    <%= render "form"%>
</div>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Articles list</h1>
<%= will_paginate @articles, list_classes: %w(pagination justify-content-center), renderer: WillPaginate::ActionView::BootstrapLinkRenderer%>
<%= render "articles" %>

app/views/articles/new.html.erb
<div>
    <h1 class="text-center mt-4">Create article</h1>
    <%= render "form"%>
</div>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>
<div class="container">
  <div class="row justify-content-center mt-4">
    <div class="col-8">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          by <%= link_to @article.user.username, @article.user %>
          <%= link_to gravatar_for(@article.user, size: 50), @article.user %>
          <% if @article.categories.any?%>
            <div class="mt-2">
              <%= render @article.categories %>
            </div>
          <% end %>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><%= simple_format(@article.description) %></div>
          <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %> 
            <%= link_to "Delete", @article, method: :delete, class: "btn btn-outline-danger", data: {confirm: "Are you sure?"} %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago, edited 
            <%= time_ago_in_words(@article.updated_at) %> ago
          </small>
        </div>
      </div>
    </div>
  </div>
  <div class="text-center">
      <%= link_to "[ Return to articles list ]", articles_path %> 
  </div>
</div>

app/views/categories/_categories.html.erb
<div class="container">
  <div class="row justify-content-center mt-4 ">
    <% @categories.each do |category| %>
      <div class="col-10 col-md-6">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
              <h5 class="card-title"><%= link_to category.name, category, class: "text-success" %> </h5>
              <p class="card-text"><%= pluralize(category.articles.count, "article") %> </p>
              <div class="text-center mt-4">
                <%= link_to "View category", category, class: "btn btn-outline-success" %>
                <% if logged_in? && current_user.admin? %>
                  <%= link_to "Edit category", edit_category_path(category), class: "btn btn-outline-info" %>
                  <%= link_to "Delete category", category_path(category), method: :delete, class: "btn btn-outline-danger", data: { confirm: "Are you sure?" } %>
                <% end %>
              </div>
          </div>
          <div class="card-footer text-muted">
              <small>Created <%= time_ago_in_words(category.created_at) %> ago, edited 
              <%= time_ago_in_words(category.updated_at) %> ago
              </small>
          </div>
        </div>
      </div>
    <% end %> 
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category, class: "badge badge-pill badge-info mr-1" %>

app/views/categories/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render "shared/errors", object: @category %>
            <%= form_with(model: @category, class: "shadow p-3 bg-light rounded", local: true) do |form| %>
                <div class="form-group row" justify-content>
                    <%= form.label :name, "Category name",class: "col-2 col-form-label" %>
                    <div class="col-10">
                        <%= form.text_field :name, placeholder: "Category name", class: "form-control shadow rounded" %>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <%= form.submit class: "btn btn-outline-success shadow rounded" %>
                </div>
            <% end %>
        </div>
    </div>
    <div class="text-center mt-4">
        <%= link_to "[ Return to categories list ]", categories_path %> 
    </div>
</div>

app/views/categories/edit.html.erb
<div>
    <h1 class="text-center mt-4">Edit category</h1>
    <%= render "form"%>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories list</h1>
<%= will_paginate @categories, list_classes: %w(pagination justify-content-center), renderer: WillPaginate::ActionView::BootstrapLinkRenderer%>
<%= render "categories" %>

app/views/categories/new.html.erb
<div>
    <h1 class="text-center mt-4">Create a new category</h1>
    <%= render "form"%>
</div>

app/views/categories/show.html.erb
<h2 class="text-center mt-4"><%= @category.name %> category</h2>
<% if logged_in? && current_user %>
  <div class="text-center mt-4">
    <%= link_to "Edit category", edit_category_path(@category), container: false, class: "btn btn-outline-info" %>
    <%= link_to "Delete category", category_path(@category), method: :delete, class: "btn btn-outline-danger", data: { confirm: "Are you sure?" } %>
  </div>
<% end %>
<h3 class="text-center mt-4">Articles</h3>
<%= will_paginate @articles, list_classes: %w(pagination justify-content-center), renderer: WillPaginate::ActionView::BootstrapLinkRenderer%>
<%= render "articles/articles" %>

app/views/layouts/_footer.html.erb
<footer class="py-4 bg-dark text-center text-white">
    <div>
        <small>Copytright &copy; alpha blog</small>
    </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav" style="flex:auto">
      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Articles list", articles_path, class: "dropdown-item" %>
          <%= link_to "Create article", new_article_path, class: "dropdown-item" if logged_in? %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="categoriesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="categoriesDropdown">
          <%= link_to "View categories", categories_path, class: "dropdown-item" %>
          <%= link_to "Create a new category", new_category_path, class: "dropdown-item" if logged_in? && current_user.admin? %>
        </div>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown ml-auto">
          <a class="nav-link dropdown-toggle" href="#" id="accountDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "(Admin)" if current_user.admin?%> <%=current_user.username %>
          </a>
          <div class="dropdown-menu" aria-labelledby="accountDropdown">
            <%= link_to "Profile", current_user, class: "dropdown-item" %>
            <%= link_to "Edit profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", logout_path, class: "dropdown-item", method: :delete %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log in", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <%# <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alpha-blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render "layouts/navbar" %>
    <div class="page-content">
      <%= render "shared/messages" %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container mt-4">
    <div class="jumbotron text-center text-white">
        <h1 class="display-4">Alpha blog</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <%= link_to "Sign Up" ,signup_path, class: "btn btn-success btn-lg" %>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <% object.errors.full_messages.each do |message| %>
            <%= message %><br/>
        <% end %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

app/views/shared/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %> 
    <div class="alert alert-<%= name=="notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %> 
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>
  

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Articles list", articles_path, class: "dropdown-item" %>
          <%= link_to "Create article", new_article_path, class: "dropdown-item" %>
        </div>
      </li>
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to current_user.username, current_user, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", logout_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log in", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/users/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8">
            <%= render "shared/errors", object: @user %>
            <%= form_with(model: @user, class: "shadow p-3 bg-light rounded", local: true) do |form| %>
                <div class="form-group" justify-content>
                    <%= form.label :username, class: "form-label" %>
                    <%= form.text_field :username, placeholder: "username", class: "form-control shadow rounded" %>
                </div>
                <div class="form-group">
                    <%= form.label :email, class: "form-label" %>
                    <%= form.text_field :email, placeholder: "user@example.com", class: "form-control shadow rounded" %>
                </div>
                <div class="form-group">
                    <%= form.label :password, class: "form-label" %>
                    <%= form.password_field :password, placeholder: "password", class: "form-control shadow rounded" %>
                </div>
                <div class="form-group d-flex justify-content-center">
                    <%= form.submit @user.new_record? ? "Sign Up" : "Update account",class: "btn btn-outline-success shadow rounded" %>
                </div>
            <% end %>
        </div>
    </div>
    <div class="text-center mt-4">
        <%= link_to "[ Return to home ]", root_path %> 
    </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit profile</h1>
<%= render "form"%>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Bloggers</h1>
<%= will_paginate @users, list_classes: %w(pagination justify-content-center), renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
<div class="container">
  <div class="row justify-content-center mt-4 ">
    <% @users.each do |user| %>
        <div class="col-8">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
              <%= link_to user.username, user, class: "font-italic" %>
            </div>
            <div class="card-body">
              <h5 class="card-title">
                <%= link_to gravatar_for(user, size: 100), user %>
              </h5>
              <p class="card-text"><%= pluralize(user.articles.count, "article") %> </p>
              <%= link_to "View profile", user, class: "btn btn-outline-success" %> 
              <% if logged_in? %>
                <% if user == current_user %>
                  <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %> 
                <% end %>
                <% if user == current_user || current_user.admin? %>
                  <%= link_to "Delete user", user, method: :delete, class: "btn btn-outline-danger",
                                                  data: { confirm: "Are you sure?" } %>
                <% end %>
              <% end %>
            </div>
            <div class="card-footer text-muted">
              <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
            </div>
          </div>
        </div>
    <% end %> 
  </div>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign Up</h1>
<%= render "form"%>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>
<%= gravatar_for(@user, {size: 200}) %>
<% if logged_in? && @user==current_user %>
  <div class="text-center mt-4">
    <%= link_to "Edit your profile", edit_user_path(@user), container: false, class: "btn btn-outline-info" %>
    <%= link_to "Delete profile", user_path(current_user), method: :delete, class: "btn btn-outline-danger", data: { confirm: "Are you sure?" } %>
  </div>
<% end %>
<h3 class="text-center mt-4">Articles</h3>
<%= will_paginate @articles, list_classes: %w(pagination justify-content-center), renderer: WillPaginate::ActionView::BootstrapLinkRenderer%>
<%= render "articles/articles" %>